# Problem 11: Find the Difference
# You are given two strings s and t.
# String t is generated by randomly shuffling string s 
# and then adding one more letter at a random position. 
# Return the letter that was added to t.
# Examples:
# s = "abcd", t = "abcde" → "e"
# s = "", t = "y" → "y"
# s = "a", t = "aa" → "a"

def find_the_difference(s: str, t: str) -> str:
    if not s:
        return t
    s1 = sorted(list(s))
    t1 = sorted(list(t))
    for i in range(len(s1)):
        if s1[i] != t1[i]:
            return t1[i]
         
    return t1[-1]    


print(find_the_difference(s = "abcd", t = "abcde"))
print(find_the_difference(s = "", t = "y"))
print(find_the_difference(s = "a", t = "aa"))


# ## Using Counter...
# from collections import Counter

# def find_the_difference(s: str, t: str) -> str:
#     count = Counter(t) - Counter(s)
#     return next(iter(count))

## Using Sum of ASCII values
# def find_the_difference(s: str, t: str) -> str:
#     total = 0

#     for ch in t:
#         total += ord(ch)

#     for ch in s:
#         total -= ord(ch)

#     return chr(total)